taskdir: tasks
app:
  expose: 0.0.0.0
  port: 8080
  allowed_domains:
    - "*"
  statuses:
    init: INIT
    done: DONE
    failed: FAILED
aws:
  access_key: your_aws_access_key
  secret_access_key: your_aws_secret_access_key
  task_bucket: deepimposter
  profile_name: default
auth:
  secret_key: your_auth_secret_key
swap:
  arc_path: arcface_model/arcface_checkpoint.tar
  crop_size: 512
stream:
  crop_size: 512
  output_dir: temp_results
  output_path: temp_results/stream.mp4
  temp_face_path: temp_results/stream_face
